//! Activities: every side effect in the system lives here.
//!
//! Two things this module demonstrates:
//!
//! 1. **Dependency injection** -- the struct holds `Arc<Deps>`, methods take
//!    `self: Arc<Self>`. That receiver is required by the `#[activities]` macro
//!    for any method that wants instance state.
//! 2. **Idempotency** -- side effects are keyed so that a retried Activity does
//!    not duplicate work.

use std::{sync::Arc, time::Duration};

use serde::{Deserialize, Serialize};
use temporalio_macros::activities;
use temporalio_sdk::{
    ApplicationFailure,
    activities::{ActivityContext, ActivityError},
};

use crate::deps::{Deps, PaymentError};

/// Error type names, referenced by the Workflow's retry policies.
///
/// These strings are the contract between "what went wrong" and "should we try
/// again". Keep them in one place; a typo silently turns a non-retryable error
/// back into a retryable one.
pub mod error_types {
    pub const CARD_DECLINED: &str = "CardDeclined";
    pub const OUT_OF_STOCK: &str = "OutOfStock";
}

// ---------------------------------------------------------------------------
// Activity inputs / outputs
// ---------------------------------------------------------------------------
//
// Any `serde::Serialize + DeserializeOwned` type works as a payload -- the SDK
// has a blanket impl. Prefer named structs over tuples: adding a field to a
// struct is backward compatible with in-flight Workflows, changing a tuple's
// arity is not.

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReserveInventory {
    pub order_id: String,
    pub sku: String,
    pub quantity: u32,
    /// Stable across every retry of this Activity. Generated by the Workflow.
    pub idempotency_key: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChargePayment {
    pub order_id: String,
    pub amount_cents: u64,
    pub idempotency_key: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShipOrder {
    pub order_id: String,
    pub parcel_count: u32,
}

// ---------------------------------------------------------------------------
// The Activity struct -- this is the DI container
// ---------------------------------------------------------------------------

pub struct OrderActivities {
    deps: Arc<Deps>,
}

impl OrderActivities {
    pub fn new(deps: Arc<Deps>) -> Self {
        Self { deps }
    }
}

#[activities]
impl OrderActivities {
    /// Reserve stock.
    ///
    /// Note the receiver: `self: Arc<Self>`. The `#[activities]` macro requires
    /// exactly this form for stateful Activities, and the parameter order is
    /// fixed: `self`, then `ActivityContext`, then your input.
    #[activity]
    pub async fn reserve_inventory(
        self: Arc<Self>,
        ctx: ActivityContext,
        input: ReserveInventory,
    ) -> Result<String, ActivityError> {
        tracing::info!(
            order_id = %input.order_id,
            attempt = ctx.info().attempt,
            "reserving inventory"
        );

        if input.quantity == 0 {
            // Non-retryable: no amount of retrying fixes a bad request. The
            // `type_name` is what the retry policy matches on.
            return Err(ActivityError::application(
                ApplicationFailure::builder("quantity must be > 0")
                    .type_name(error_types::OUT_OF_STOCK.to_string())
                    .non_retryable(true)
                    .build(),
            ));
        }

        // Idempotent write: if this Activity already ran and the worker died
        // before reporting success, we return the same reservation id.
        let reservation_id = format!("resv_{}", input.idempotency_key);
        let stored = self
            .deps
            .db
            .upsert_reservation(&input.idempotency_key, &reservation_id)
            .await;

        Ok(stored)
    }

    /// Charge the customer. This is the one that must never double-run.
    #[activity]
    pub async fn charge_payment(
        self: Arc<Self>,
        ctx: ActivityContext,
        input: ChargePayment,
    ) -> Result<String, ActivityError> {
        let attempt = ctx.info().attempt;
        tracing::info!(order_id = %input.order_id, attempt, "charging payment");

        // Layer 1: our own dedupe table. If a previous attempt succeeded at the
        // gateway but crashed before returning, we find the charge here.
        if let Some(existing) = self.deps.db.find_charge(&input.idempotency_key).await {
            tracing::info!(charge_id = %existing, "charge already recorded; skipping gateway");
            return Ok(existing);
        }

        // Layer 2: the provider's own idempotency key. Belt and braces -- this
        // is what saves you if the crash happens between the gateway call and
        // our database write.
        let charge_id = self
            .deps
            .payments
            .charge(&input.order_id, input.amount_cents, &input.idempotency_key)
            .await
            .map_err(|e| match e {
                // Map domain errors onto Temporal's retry semantics. Getting
                // this mapping right is most of what "good retries" means.
                PaymentError::Declined(msg) => ActivityError::application(
                    ApplicationFailure::builder(msg)
                        .type_name(error_types::CARD_DECLINED.to_string())
                        .non_retryable(true)
                        .build(),
                ),
                // Retryable: the default. Just return a plain application
                // failure and let the retry policy back off.
                PaymentError::Unavailable(msg) => {
                    ActivityError::application(ApplicationFailure::new(msg))
                }
            })?;

        self.deps
            .db
            .upsert_charge(&input.idempotency_key, &charge_id)
            .await;

        Ok(charge_id)
    }

    /// Compensation for `charge_payment`.
    #[activity]
    pub async fn refund_payment(
        self: Arc<Self>,
        _ctx: ActivityContext,
        charge_id: String,
    ) -> Result<(), ActivityError> {
        self.deps
            .payments
            .refund(&charge_id)
            .await
            .map_err(|e| ActivityError::application(ApplicationFailure::new(e.to_string())))?;
        Ok(())
    }

    /// Compensation for `reserve_inventory`.
    #[activity]
    pub async fn release_inventory(
        self: Arc<Self>,
        _ctx: ActivityContext,
        reservation_id: String,
    ) -> Result<(), ActivityError> {
        self.deps.db.delete_reservation(&reservation_id).await;
        tracing::info!(reservation_id, "released inventory");
        Ok(())
    }

    /// A long-running Activity that heartbeats.
    ///
    /// Heartbeating buys two things:
    ///   * the server notices a dead worker within `heartbeat_timeout` instead
    ///     of waiting out the whole `start_to_close_timeout`;
    ///   * progress details survive into the next attempt, so a retry resumes
    ///     instead of restarting.
    #[activity]
    pub async fn ship_order(
        self: Arc<Self>,
        ctx: ActivityContext,
        input: ShipOrder,
    ) -> Result<String, ActivityError> {
        // Resume from wherever the previous attempt got to.
        let start_at: u32 = ctx
            .heartbeat_details()
            .deserialize()
            .ok()
            .flatten()
            .unwrap_or(0);

        tracing::info!(
            order_id = %input.order_id,
            attempt = ctx.info().attempt,
            start_at,
            "shipping"
        );

        for parcel in start_at..input.parcel_count {
            // Cooperative cancellation: if the Workflow is cancelled, bail out
            // cleanly rather than being killed mid-parcel.
            if ctx.is_cancelled() {
                return Err(ActivityError::Cancelled { details: None });
            }

            tokio::time::sleep(Duration::from_millis(200)).await;

            // Record progress. Cheap and non-blocking -- the SDK batches these.
            let _ = ctx.record_heartbeat(parcel + 1).await;
        }

        Ok(format!("shipped {} parcels", input.parcel_count))
    }
}
